version: '3.8'

services:

    ghost:
        image: ghost:5.32.0
        container_name: ghost
        volumes:
            - ./ghost/config:/var/lib/ghost/config:z
            - ./ghost/content:/var/lib/ghost/content:z
        ports:
            -   2368:2368
        environment:
            - NODE_ENV=${NODE_ENV}
            - url=${APP_URL}
            - database__client=mysql
            - database__connection__host=mysql
            - database__connection__user=root
            - database__connection__password=${MYSQL_ROOT_PASSWORD}
            - database__connection__database=${MYSQL_DATABASE}
            - server__host=0.0.0.0
            - server__port=2368
            - mail__transport=SMTP
            - mail__options__service=Postmark
            - mail__options__port=2525
            - mail__options__host=smtp.postmarkapp.com
            - mail__options__auth__user=${ACCESS_KEY}
            - mail__options__auth__pass=${SECRET_KEY}
        restart: always
        links:
            -   mysql

    mysql:
        image: mysql:8.0
        container_name: mysql
        expose:
            -   3306
        volumes:
            - ./mysql/data:/var/lib/mysql:z
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        restart: always
